Document: 2048
Title: Debian 2048 Manual
Author: <insert document author here>
Abstract: This manual describes what 2048 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/2048/2048.sgml.gz

Format: postscript
Files: /usr/share/doc/2048/2048.ps.gz

Format: text
Files: /usr/share/doc/2048/2048.text.gz

Format: HTML
Index: /usr/share/doc/2048/html/index.html
Files: /usr/share/doc/2048/html/*.html
